[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  HUGO_VERSION = "0.148.1"
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"